projects:
  quizapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/API.service.ts
        docsFilePath: src/graphql
        maxDepth: 4
extensions:
  amplify:
    version: 3
