/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:37c04831-d8d9-4690-a01a-5fd7ef485c0f",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_j6ajZR27g",
  aws_user_pools_web_client_id: "5cpaph3kbm0tekqoffmtpq0e4j",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://kle735obprfujgu7mqciwr6tny.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
};

export default awsmobile;
